server:
  port: 8090

spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/blogdb
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create